### ISSUE TITLE
Can you add a flag for the API calls?

### ISSUE THREAD

**Issue by santhony7** [pippinsplugins/Simple-Post-Expiration#10]
The only thing I see is "Expired:" in the title. It'd be nice if there was just a boolean.

**Comment by pippinsplugins** [comment]
Are you referring the a flag in the WP REST API?

**Comment by santhony7** [comment]
Sorry i wasn't more clear. Yes sir, the REST API.

**Comment by santhony7** [comment]
Better yet....if possible...don't have the post return in the API. This is what it does for posts scheduled in the future. You might even be able to do just that: schedule deleted posts for 20 years from now. :-)

**Comment by santhony7** [comment]
Or..... something like this. I'm trying to add it to your code but I have NO idea what I am doing.

`wp_update_post(array(
        	'ID'    =>  $post_id,
        	'post_status'   =>  'draft'
        ));`
