### ISSUE TITLE
Ability to set Expiry Never

### ISSUE THREAD

**Issue by AttractionsNearMe** [pippinsplugins/Simple-Post-Expiration#6]
I think the plugin is brilliant but occasionally I write the odd post that I do not want to expire, would it be possible to add a never expires option?

**Comment by mindctrl** [comment]
@AttractionsNearMe the plugin defaults to Never.

![image](https://cloud.githubusercontent.com/assets/1254870/18932386/2155b6f8-859e-11e6-9698-9a8a80e53204.png)
